version: "3.9"
services:
  myportal:
    image: drogonframework/drogon
    command: /root/myportal/execute.sh
    container_name: myportal
    volumes:
      - .:/root/myportal
    ports:
      - "49153:49153"